import { Router } from "express";

import { permissions } from "../../shared/auth/permissions.js";
import { asyncHandler } from "../../shared/http/async-handler.js";
import { requireAuth } from "../../shared/middleware/auth.middleware.js";
import { requirePermission } from "../../shared/middleware/rbac.middleware.js";
import { requireTenant } from "../../shared/middleware/tenant.middleware.js";
import {
  createAccountController,
  createActivityController,
  createCandidateController,
  createContactController,
  createInterviewController,
  createLeadController,
  createOpportunityController,
  createPlacementController,
  createProposalController,
  createProposalVersionController,
  createRequirementController,
  createSubmissionController,
  createVendorController,
  convertLeadController,
  decideProposalController,
  deleteAccountController,
  deleteActivityController,
  deleteCandidateController,
  deleteContactController,
  deleteInterviewController,
  deleteLeadController,
  deleteOpportunityController,
  deletePlacementController,
  deleteProposalController,
  deleteRequirementController,
  deleteSubmissionController,
  deleteVendorController,
  getAccountController,
  getActivityController,
  getCandidateController,
  getContactController,
  getInterviewController,
  getLeadController,
  getOpportunityController,
  getPlacementController,
  getProposalController,
  getRequirementController,
  getSubmissionController,
  getVendorController,
  listAccountsController,
  listActivitiesController,
  listCandidatesController,
  listContactsController,
  listInterviewsController,
  listLeadsController,
  listOpportunitiesController,
  listPlacementsController,
  listOpportunityPipelineController,
  listProposalsController,
  listRequirementSubmissionsController,
  listRequirementsController,
  listSubmissionsController,
  listVendorsController,
  requestProposalPdfExportController,
  submitProposalController,
  updateAccountController,
  updateActivityController,
  updateCandidateController,
  updateContactController,
  updateInterviewController,
  updateLeadController,
  updateOpportunityController,
  updatePlacementController,
  updateProposalController,
  updateRequirementController,
  updateSubmissionController,
  updateVendorController,
} from "./crm.controller.js";

export const crmRouter = Router();

crmRouter.use(requireAuth, requireTenant);

crmRouter.get(
  "/leads",
  requirePermission(permissions.leadsRead),
  asyncHandler(listLeadsController),
);
crmRouter.post(
  "/leads",
  requirePermission(permissions.leadsCreate),
  asyncHandler(createLeadController),
);
crmRouter.get(
  "/leads/:leadId",
  requirePermission(permissions.leadsRead),
  asyncHandler(getLeadController),
);
crmRouter.patch(
  "/leads/:leadId",
  requirePermission(permissions.leadsUpdate),
  asyncHandler(updateLeadController),
);
crmRouter.delete(
  "/leads/:leadId",
  requirePermission(permissions.leadsDelete),
  asyncHandler(deleteLeadController),
);
crmRouter.post(
  "/leads/:leadId/convert",
  requirePermission(permissions.opportunitiesCreate),
  asyncHandler(convertLeadController),
);

crmRouter.get(
  "/opportunities",
  requirePermission(permissions.opportunitiesRead),
  asyncHandler(listOpportunitiesController),
);
crmRouter.get(
  "/opportunities/pipeline",
  requirePermission(permissions.opportunitiesRead),
  asyncHandler(listOpportunityPipelineController),
);
crmRouter.post(
  "/opportunities",
  requirePermission(permissions.opportunitiesCreate),
  asyncHandler(createOpportunityController),
);
crmRouter.get(
  "/opportunities/:opportunityId",
  requirePermission(permissions.opportunitiesRead),
  asyncHandler(getOpportunityController),
);
crmRouter.patch(
  "/opportunities/:opportunityId",
  requirePermission(permissions.opportunitiesUpdate),
  asyncHandler(updateOpportunityController),
);
crmRouter.delete(
  "/opportunities/:opportunityId",
  requirePermission(permissions.opportunitiesDelete),
  asyncHandler(deleteOpportunityController),
);

crmRouter.get(
  "/proposals",
  requirePermission(permissions.proposalsRead),
  asyncHandler(listProposalsController),
);
crmRouter.post(
  "/proposals",
  requirePermission(permissions.proposalsCreate),
  asyncHandler(createProposalController),
);
crmRouter.get(
  "/proposals/:proposalId",
  requirePermission(permissions.proposalsRead),
  asyncHandler(getProposalController),
);
crmRouter.patch(
  "/proposals/:proposalId",
  requirePermission(permissions.proposalsUpdate),
  asyncHandler(updateProposalController),
);
crmRouter.post(
  "/proposals/:proposalId/versions",
  requirePermission(permissions.proposalsUpdate),
  asyncHandler(createProposalVersionController),
);
crmRouter.post(
  "/proposals/:proposalId/submit",
  requirePermission(permissions.proposalsUpdate),
  asyncHandler(submitProposalController),
);
crmRouter.post(
  "/proposals/:proposalId/decision",
  requirePermission(permissions.proposalsApprove),
  asyncHandler(decideProposalController),
);
crmRouter.post(
  "/proposals/:proposalId/pdf-export",
  requirePermission(permissions.proposalsRead),
  asyncHandler(requestProposalPdfExportController),
);
crmRouter.delete(
  "/proposals/:proposalId",
  requirePermission(permissions.proposalsDelete),
  asyncHandler(deleteProposalController),
);

crmRouter.get(
  "/activities",
  requirePermission(permissions.activitiesRead),
  asyncHandler(listActivitiesController),
);
crmRouter.post(
  "/activities",
  requirePermission(permissions.activitiesCreate),
  asyncHandler(createActivityController),
);
crmRouter.get(
  "/activities/:activityId",
  requirePermission(permissions.activitiesRead),
  asyncHandler(getActivityController),
);
crmRouter.patch(
  "/activities/:activityId",
  requirePermission(permissions.activitiesUpdate),
  asyncHandler(updateActivityController),
);
crmRouter.delete(
  "/activities/:activityId",
  requirePermission(permissions.activitiesDelete),
  asyncHandler(deleteActivityController),
);

crmRouter.get(
  "/vendors",
  requirePermission(permissions.vendorsRead),
  asyncHandler(listVendorsController),
);
crmRouter.post(
  "/vendors",
  requirePermission(permissions.vendorsCreate),
  asyncHandler(createVendorController),
);
crmRouter.get(
  "/vendors/:vendorId",
  requirePermission(permissions.vendorsRead),
  asyncHandler(getVendorController),
);
crmRouter.patch(
  "/vendors/:vendorId",
  requirePermission(permissions.vendorsUpdate),
  asyncHandler(updateVendorController),
);
crmRouter.delete(
  "/vendors/:vendorId",
  requirePermission(permissions.vendorsDelete),
  asyncHandler(deleteVendorController),
);

crmRouter.get(
  "/candidates",
  requirePermission(permissions.candidatesRead),
  asyncHandler(listCandidatesController),
);
crmRouter.post(
  "/candidates",
  requirePermission(permissions.candidatesCreate),
  asyncHandler(createCandidateController),
);
crmRouter.get(
  "/candidates/:candidateId",
  requirePermission(permissions.candidatesRead),
  asyncHandler(getCandidateController),
);
crmRouter.patch(
  "/candidates/:candidateId",
  requirePermission(permissions.candidatesUpdate),
  asyncHandler(updateCandidateController),
);
crmRouter.delete(
  "/candidates/:candidateId",
  requirePermission(permissions.candidatesDelete),
  asyncHandler(deleteCandidateController),
);

crmRouter.get(
  "/requirements",
  requirePermission(permissions.requirementsRead),
  asyncHandler(listRequirementsController),
);
crmRouter.post(
  "/requirements",
  requirePermission(permissions.requirementsCreate),
  asyncHandler(createRequirementController),
);
crmRouter.get(
  "/requirements/:requirementId",
  requirePermission(permissions.requirementsRead),
  asyncHandler(getRequirementController),
);
crmRouter.patch(
  "/requirements/:requirementId",
  requirePermission(permissions.requirementsUpdate),
  asyncHandler(updateRequirementController),
);
crmRouter.delete(
  "/requirements/:requirementId",
  requirePermission(permissions.requirementsDelete),
  asyncHandler(deleteRequirementController),
);
crmRouter.get(
  "/requirements/:requirementId/submissions",
  requirePermission(permissions.submissionsRead),
  asyncHandler(listRequirementSubmissionsController),
);
crmRouter.post(
  "/requirements/:requirementId/submissions",
  requirePermission(permissions.submissionsCreate),
  asyncHandler(createSubmissionController),
);
crmRouter.get(
  "/submissions",
  requirePermission(permissions.submissionsRead),
  asyncHandler(listSubmissionsController),
);
crmRouter.get(
  "/submissions/:submissionId",
  requirePermission(permissions.submissionsRead),
  asyncHandler(getSubmissionController),
);
crmRouter.patch(
  "/submissions/:submissionId",
  requirePermission(permissions.submissionsUpdate),
  asyncHandler(updateSubmissionController),
);
crmRouter.delete(
  "/submissions/:submissionId",
  requirePermission(permissions.submissionsDelete),
  asyncHandler(deleteSubmissionController),
);

crmRouter.get(
  "/interviews",
  requirePermission(permissions.interviewsRead),
  asyncHandler(listInterviewsController),
);
crmRouter.post(
  "/interviews",
  requirePermission(permissions.interviewsCreate),
  asyncHandler(createInterviewController),
);
crmRouter.get(
  "/interviews/:interviewId",
  requirePermission(permissions.interviewsRead),
  asyncHandler(getInterviewController),
);
crmRouter.patch(
  "/interviews/:interviewId",
  requirePermission(permissions.interviewsUpdate),
  asyncHandler(updateInterviewController),
);
crmRouter.delete(
  "/interviews/:interviewId",
  requirePermission(permissions.interviewsDelete),
  asyncHandler(deleteInterviewController),
);

crmRouter.get(
  "/placements",
  requirePermission(permissions.placementsRead),
  asyncHandler(listPlacementsController),
);
crmRouter.post(
  "/placements",
  requirePermission(permissions.placementsCreate),
  asyncHandler(createPlacementController),
);
crmRouter.get(
  "/placements/:placementId",
  requirePermission(permissions.placementsRead),
  asyncHandler(getPlacementController),
);
crmRouter.patch(
  "/placements/:placementId",
  requirePermission(permissions.placementsUpdate),
  asyncHandler(updatePlacementController),
);
crmRouter.delete(
  "/placements/:placementId",
  requirePermission(permissions.placementsDelete),
  asyncHandler(deletePlacementController),
);

crmRouter.get(
  "/accounts",
  requirePermission(permissions.accountsRead),
  asyncHandler(listAccountsController),
);
crmRouter.post(
  "/accounts",
  requirePermission(permissions.accountsCreate),
  asyncHandler(createAccountController),
);
crmRouter.get(
  "/accounts/:accountId",
  requirePermission(permissions.accountsRead),
  asyncHandler(getAccountController),
);
crmRouter.patch(
  "/accounts/:accountId",
  requirePermission(permissions.accountsUpdate),
  asyncHandler(updateAccountController),
);
crmRouter.delete(
  "/accounts/:accountId",
  requirePermission(permissions.accountsDelete),
  asyncHandler(deleteAccountController),
);

crmRouter.get(
  "/contacts",
  requirePermission(permissions.contactsRead),
  asyncHandler(listContactsController),
);
crmRouter.post(
  "/contacts",
  requirePermission(permissions.contactsCreate),
  asyncHandler(createContactController),
);
crmRouter.get(
  "/contacts/:contactId",
  requirePermission(permissions.contactsRead),
  asyncHandler(getContactController),
);
crmRouter.patch(
  "/contacts/:contactId",
  requirePermission(permissions.contactsUpdate),
  asyncHandler(updateContactController),
);
crmRouter.delete(
  "/contacts/:contactId",
  requirePermission(permissions.contactsDelete),
  asyncHandler(deleteContactController),
);
