export const permissions = {
  accountsCreate: "accounts:create",
  accountsDelete: "accounts:delete:all",
  accountsRead: "accounts:read:all",
  accountsUpdate: "accounts:update:all",
  aiSettingsManage: "ai-settings:manage",
  adminSettingsManage: "admin-settings:manage",
  auditRead: "audit:read",
  contactsCreate: "contacts:create",
  contactsDelete: "contacts:delete:all",
  contactsRead: "contacts:read:all",
  contactsUpdate: "contacts:update:all",
  leadsCreate: "leads:create",
  leadsDelete: "leads:delete:all",
  leadsRead: "leads:read:all",
  leadsUpdate: "leads:update:all",
  opportunitiesCreate: "opportunities:create",
  opportunitiesDelete: "opportunities:delete:all",
  opportunitiesRead: "opportunities:read:all",
  opportunitiesUpdate: "opportunities:update:all",
  proposalsApprove: "proposals:approve",
  proposalsCreate: "proposals:create",
  proposalsDelete: "proposals:delete:all",
  proposalsRead: "proposals:read:all",
  proposalsUpdate: "proposals:update:all",
  activitiesCreate: "activities:create",
  activitiesDelete: "activities:delete:all",
  activitiesRead: "activities:read:all",
  activitiesUpdate: "activities:update:all",
  rolesManage: "roles:manage",
  tenantsManage: "tenants:manage",
  usersManage: "users:manage",
} as const;

export type PermissionKey = (typeof permissions)[keyof typeof permissions];
